// <auto-generated />
namespace EnrollmentApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1014_Update2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1014_Update2));
        
        string IMigrationMetadata.Id
        {
            get { return "201810141349205_1014_Update2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
