// <auto-generated />
namespace EventFinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FinalSeed_Migration_EventFinderDB_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinalSeed_Migration_EventFinderDB_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201812100146359_FinalSeed_Migration_EventFinderDB_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
